server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/414?useunicode=true&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: Zbw574601!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
